# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_sum <- function(i) {
    .Call(`_hardyr_log_sum`, i)
}

log_n_choose_k <- function(n, k) {
    .Call(`_hardyr_log_n_choose_k`, n, k)
}

probability_of_M_pairs <- function(N, K, M) {
    .Call(`_hardyr_probability_of_M_pairs`, N, K, M)
}

